name = "sud0-exposed"
compatibility_date = "2026-06-06"
compatibility_flags = ["nodejs_compat"]
main = "@tanstack/react-start/server-entry"

routes = [
  { pattern = "exposed.sud0.dev", custom_domain = true },
]

[observability]
enabled = true
